version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    # volumes:
      # - postgres:/var/lib/mysql
      # - ./initdb:/docker-entrypoint-initdb.d 
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: test
      
# volumes:
  # postgres:
    # driver: local
